export const SUBREDDIT_REQUEST = 'SUBREDDIT_REQUEST';
export const SUBREDDIT_SUCCESS = 'SUBREDDIT_SUCCESS';
export const SUBREDDIT_FAILURE = 'SUBREDDIT_FAILURE';

export const SUBREDDITLIST = 'SUBREDDITLIST';
export const SUBREDDITHIDE = 'SUBREDDITHIDE';